// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // El CLI (migraciones/introspección) usa la conexión directa;
    // la app en runtime usa DATABASE_URL a través del driver adapter.
    url: process.env["DIRECT_URL"],
    // `prisma migrate dev` necesita una base shadow para calcular el diff.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
